Added aop23_from_script_052323.ttl
ExposuresProvider/noctua-models pull request #6
Opened 2023-05-23 17:58 UTC by mam288

Addresses issues #1  and #2

2023-05-24 19:54 UTC, mam288 commented
Added .owl and .ofn files for AOP23

2023-05-25 20:05 UTC, balhoff requested changes
@mam288 a few change requests that we should probably put in a specs document:
- Only commit turtle format files here, one file for each model.
- Put all models in a `models` folder under the project root
- Make sure each model declares an ontology IRI, using a triple like this: `<https://noctua.apps.renci.org/model/some_identifier> a owl:Ontology`
- Make sure the filename matches the local part of the ontology IRI, like `some_identifier.ttl`
- Don't include any `owl:imports` triples.

Let me know if you have any questions!

2023-05-25 20:13 UTC, mam288 commented
@balhoff Will do, thanks Jim! Just to clarify, you only want the .ttl file? You don't want me to use robot to convert them to .owl or .opn files?

2023-05-25 20:15 UTC, balhoff commented
Right, the robot conversion was just to validate parseability for you.

2023-05-25 20:19 UTC, mam288 commented
Ahh I see. Thanks! 
Also for the IRI statement I use Noctua's address and then use an identifier (AOP_23), right?  (see below)
<https://noctua.apps.renci.org/model/AOP_23>. 
I should then name the matching .ttl file AOP_23.ttl?

2023-05-26 14:32 UTC, balhoff commented
> Ahh I see. Thanks!
> Also for the IRI statement I use Noctua's address and then use an identifier (AOP_23), right? (see below)
> https://noctua.apps.renci.org/model/AOP_23.
> I should then name the matching .ttl file AOP_23.ttl?

Yes, that's it.

2023-05-26 14:57 UTC, mam288 commented
@balhoff I added .ttl files for all of the models that ran successfully. Can you just check that they look correct and then upload to Noctua if they do? Thanks!

2023-05-26 18:09 UTC, balhoff requested changes

2023-05-26 18:09 UTC, balhoff commented on models/aop_100.ttl
> +	<http://purl.obolibrary.org/obo/D005298> ;
@mam288 just noticed this ID—is it a typo for `DO_`? Can you check for others?

2023-06-06 16:14 UTC, balhoff requested changes
@mam288 I noticed a couple more issues that maybe we should fix before loading.

2023-06-06 16:14 UTC, balhoff commented on models/aop_101.ttl
> +	<http://purl.obolibrary.org/obo/> :population_growth_rate  .
@mam288 I think there's a missing part of a relation ID here.

2023-06-06 16:14 UTC, balhoff commented on models/aop_101.ttl
> +	<http://purl.obolibrary.org/obo/> :population_growth_rate  .
This happens in some other files as well.

2023-06-06 21:50 UTC, mam288 commented
@balhoff There are some cases where the code couldn't predict a relationship (similar to how some have multiple relationships). I'll have to double check but I think these are those cases. The statement is supposed to be a placeholder. Is there a better way to do this? Thanks!

2023-06-07 14:12 UTC, balhoff commented
> @balhoff There are some cases where the code couldn't predict a relationship (similar to how some have multiple relationships). I'll have to double check but I think these are those cases. The statement is supposed to be a placeholder. Is there a better way to do this? Thanks!

How about just using `https://w3id.org/biolink/vocab/related_to`?

2023-06-07 14:14 UTC, balhoff commented
@mam288 or if you think it makes sense for the situations you have, you could use the very general [causally related to](http://purl.obolibrary.org/obo/RO_0002410) and at least stick with an RO term.

2023-06-08 23:25 UTC, mam288 commented
@balhoff I went with causally related term for the edges without an assigned term. I uploaded new .ttl files to the "meisha" branch. Let me know if you have any questions.

2023-06-09 14:56 UTC, mam288 commented
@balhoff I updated the IRI statements for the MESH terms.

2023-06-14 18:36 UTC, balhoff approved these changes

2023-06-14 18:37 UTC, merged